### ISSUE TITLE
Fails with python-3.7

### ISSUE THREAD

**Issue by yurivict** [ycollet/psi-plugins#5]
```
  File "/disk-samsung/freebsd-ports/audio/psi-plugins-lv2/work/psi-plugins-83f318d/.waf3-1.7.11-715590adb2974ef17ddee0c7e2df2d1d/waflib/Node.py", line 282, in ant_iter
    raise StopIteration
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/disk-samsung/freebsd-ports/audio/psi-plugins-lv2/work/psi-plugins-83f318d/.waf3-1.7.11-715590adb2974ef17ddee0c7e2df2d1d/waflib/Scripting.py", line 97, in waf_entry_point
    run_commands()
  File "/disk-samsung/freebsd-ports/audio/psi-plugins-lv2/work/psi-plugins-83f318d/.waf3-1.7.11-715590adb2974ef17ddee0c7e2df2d1d/waflib/Scripting.py", line 149, in run_commands
    parse_options()
  File "/disk-samsung/freebsd-ports/audio/psi-plugins-lv2/work/psi-plugins-83f318d/.waf3-1.7.11-715590adb2974ef17ddee0c7e2df2d1d/waflib/Scripting.py", line 127, in parse_options
    Context.create_context('options').execute()
  File "/disk-samsung/freebsd-ports/audio/psi-plugins-lv2/work/psi-plugins-83f318d/.waf3-1.7.11-715590adb2974ef17ddee0c7e2df2d1d/waflib/Options.py", line 134, in execute
    super(OptionsContext,self).execute()
  File "/disk-samsung/freebsd-ports/audio/psi-plugins-lv2/work/psi-plugins-83f318d/.waf3-1.7.11-715590adb2974ef17ddee0c7e2df2d1d/waflib/Context.py", line 87, in execute
    self.recurse([os.path.dirname(g_module.root_path)])
  File "/disk-samsung/freebsd-ports/audio/psi-plugins-lv2/work/psi-plugins-83f318d/.waf3-1.7.11-715590adb2974ef17ddee0c7e2df2d1d/waflib/Context.py", line 128, in recurse
    user_function(self)
  File "/disk-samsung/freebsd-ports/audio/psi-plugins-lv2/work/psi-plugins-83f318d/wscript", line 24, in options
    opt.load('compiler_c')
  File "/disk-samsung/freebsd-ports/audio/psi-plugins-lv2/work/psi-plugins-83f318d/.waf3-1.7.11-715590adb2974ef17ddee0c7e2df2d1d/waflib/Context.py", line 84, in load
    fun(self)
  File "/disk-samsung/freebsd-ports/audio/psi-plugins-lv2/work/psi-plugins-83f318d/.waf3-1.7.11-715590adb2974ef17ddee0c7e2df2d1d/waflib/Tools/compiler_c.py", line 31, in options
    opt.load_special_tools('c_*.py',ban=['c_dumbpreproc.py'])
  File "/disk-samsung/freebsd-ports/audio/psi-plugins-lv2/work/psi-plugins-83f318d/.waf3-1.7.11-715590adb2974ef17ddee0c7e2df2d1d/waflib/Context.py", line 264, in load_special_tools
    lst=self.root.find_node(waf_dir).find_node('waflib/extras').ant_glob(var)
  File "/disk-samsung/freebsd-ports/audio/psi-plugins-lv2/work/psi-plugins-83f318d/.waf3-1.7.11-715590adb2974ef17ddee0c7e2df2d1d/waflib/Node.py", line 331, in ant_glob
    ret=[x for x in self.ant_iter(accept=accept,pats=[to_pat(incl),to_pat(excl)],maxdepth=25,dir=dir,src=src,remove=kw.get('remove',True))]
  File "/disk-samsung/freebsd-ports/audio/psi-plugins-lv2/work/psi-plugins-83f318d/.waf3-1.7.11-715590adb2974ef17ddee0c7e2df2d1d/waflib/Node.py", line 331, in <listcomp>
    ret=[x for x in self.ant_iter(accept=accept,pats=[to_pat(incl),to_pat(excl)],maxdepth=25,dir=dir,src=src,remove=kw.get('remove',True))]
RuntimeError: generator raised StopIteration
```

**Comment by ycollet** [comment]
Thanks for the report, I will try to work on this tonight.

**Comment by ycollet** [comment]
I am switching to cmake. I do not master waf and it's easier for me to continue with cmake ...
